#!/bin/sh

SANDBOX=/home/vagrant/hakyll/.cabal-sandbox

docker run \
  -p '8000:8000' \
  -v `pwd`:/data \
  --name=qxjit-art \
  --rm=true \
  -i \
  flipstone/hakyll \
  "cd _source && \
    cabal sandbox init --sandbox $SANDBOX && \
    cabal install && \
    site watch -h 0.0.0.0" \
  &


